class Data:
    """Данные для заполнения тестов."""

    WAIT_TIME = 10
    MAIN_PAGE_URL = "https://stellarburgers.nomoreparties.site"
    REGISTER_URL = "https://stellarburgers.nomoreparties.site/register"
    LOGIN_URL = "https://stellarburgers.nomoreparties.site/login"
    FORGOT_PASSWORD_URL = "https://stellarburgers.nomoreparties.site/forgot-password"
    TEST_EMAIL = "piunova_15@gmail.com"
    TEST_PASSWORD = "19_09_93"
    TEST_NAME = "Natalia"
    SECTION_TITLE_TEXT = "Соберите бургер"
    LOGIN_PAGE_TITLE_TEXT = "Вход"
    TEST_INCORRECT_PASSWORD = "1234"
    INCORRECT_PASSWORD_WARNING = "Некорректный пароль"
    LOGIN_IN_ACCOUNT_BUTTON_TEXT = "Войти в аккаунт"
    PROFILE_LINK_TEXT = "Профиль"
    CONSTRUCTOR_TITLE_TEXT = "Соберите бургер"
    BREAD_TAB_TEXT = "Булки"
    SAUCES_TAB_TEXT = "Соусы"
    FILLING_TAB_TEXT = "Начинки"
